apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  labels:
    app: privileged-pod
spec:
  containers:
    - name: privileged-container
      image: docker.io/library/nginx:1.25
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
      securityContext:
        privileged: true  # This will be blocked
